name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        browser: [chrome, webkit edge, electron, firefox]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        uses: cypress-io/github-action@v4
        with:
          build: npx playwright install-deps webkit
          runTests: false
        if: ${{ matrix.browser == webkit }}

      - name: Run Component tests 🧪
        uses: cypress-io/github-action@v4
        with:
          Install: ${{ matrix.browser != webkit }}
          component: true
          browser: ${{ matrix.browser }}

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
